/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cadastro;

import dao.ClienteDAO;
import dao.EstadoDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.InternalFrameEvent;
import model.Cliente;
import model.Estado;
import view.pesquisa.BuscaCliente;
import view.movimento.VendaView;
import static view.cadastro.LoginView.emp;

/**
 *
 * @author Celso
 */
public class ClienteView extends javax.swing.JInternalFrame {

    public static String pr = "";
    private Cliente obj = null;
    private ClienteDAO dao = new ClienteDAO();

    //private Estado estado;
    private List<Estado> estados;
    //private List<Cidade> cidades;

    //private CidadeDAO cidadeDAO;
    private EstadoDAO estadoDAO;

    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
        habilitarFormulario(false);

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            @Override
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                dispose();
                Menu.menuCliente.setEnabled(true);
                //Menu.btnCliente.setEnabled(true);
            }

            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JFormattedTextField();
        rbtFisica = new javax.swing.JRadioButton();
        rbtJuridica = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        chkSituacao = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jtfCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfRua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfDataCadastro = new javax.swing.JFormattedTextField();
        jtfCpf = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jtfCnpj = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtfRazaoSocial = new javax.swing.JFormattedTextField();
        jtfBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("CLIENTES");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Clientes"));

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Novo");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNovo.setMaximumSize(new java.awt.Dimension(92, 35));
        btnNovo.setPreferredSize(new java.awt.Dimension(70, 35));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvar.setMaximumSize(new java.awt.Dimension(92, 35));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.setMaximumSize(new java.awt.Dimension(92, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        jLabel1.setText("CÓDIGO.:");

        jLabel2.setText("NOME.:");

        jtfNome.setEnabled(false);
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
        });

        jLabel3.setText("TELEFONE.:");

        jtfTelefone.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Zoom.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCodigo.setEnabled(false);
        jtfCodigo.setValue(new Double(0));

        bgTipo.add(rbtFisica);
        rbtFisica.setText("Fisica");
        rbtFisica.setEnabled(false);
        rbtFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtFisicaMouseClicked(evt);
            }
        });
        rbtFisica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtFisicaKeyPressed(evt);
            }
        });

        bgTipo.add(rbtJuridica);
        rbtJuridica.setText("Jurídica");
        rbtJuridica.setEnabled(false);
        rbtJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtJuridicaMouseClicked(evt);
            }
        });
        rbtJuridica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtJuridicaKeyPressed(evt);
            }
        });

        jLabel15.setText("TIPO.:");

        chkSituacao.setText("Ativo");
        chkSituacao.setEnabled(false);

        jLabel18.setText("SITUAÇÃO.:");

        jcbEstado.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jcbEstado.setEnabled(false);
        jcbEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbEstadoFocusLost(evt);
            }
        });
        jcbEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbEstadoMouseClicked(evt);
            }
        });

        jtfCidade.setEnabled(false);
        jtfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCidadeKeyPressed(evt);
            }
        });

        jLabel4.setText("CIDADE.:");

        jtfRua.setEnabled(false);

        jLabel5.setText("ENDEREÇO.:");

        jLabel6.setText("ESTADO.:");

        jtfNumero.setEnabled(false);

        jLabel7.setText("NÚMERO.:");

        jLabel8.setText("CADASTRO.:");

        jtfDataCadastro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfDataCadastro.setEnabled(false);

        try {
            jtfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCpf.setEnabled(false);

        jLabel20.setText("CNPJ.:");

        jtfCnpj.setEnabled(false);

        jLabel21.setText("RAZAO SOCIAL.:");

        jLabel22.setText("CPF.:");

        jtfRazaoSocial.setEnabled(false);

        jtfBairro.setEnabled(false);

        jLabel9.setText("BAIRRO.:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 302, Short.MAX_VALUE))
                    .addComponent(jtfNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rbtFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtJuridica))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfCnpj, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfRua, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(jtfCidade)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRazaoSocial)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfBairro)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcbEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(chkSituacao))
                                    .addComponent(jLabel18))))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtFisica)
                            .addComponent(rbtJuridica))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(3, 3, 3)
                        .addComponent(chkSituacao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pessoais", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Histórico", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        Novo();
    }//GEN-LAST:event_btnNovoActionPerformed

    public void Novo() {
        obj = new Cliente();
        jtfNome.requestFocus();
        habilitarFormulario(true);
        combo();
        pr = "Cadastrado";
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (validaCampos()) {
            if (!jtfCodigo.getText().equals("")) {
                obj.setId(Long.parseLong(jtfCodigo.getText()));
            }
            obj.setEmpresa(emp);
            if (rbtFisica.isSelected()) {
                obj.setTipo("F");
            } else if (rbtJuridica.isSelected()) {
                obj.setTipo("J");
            }
            obj.setNome(jtfNome.getText());
            obj.setDataCadastro(new Date());
            obj.setTelefone(jtfTelefone.getText());
            obj.setRua(jtfRua.getText());
            obj.setNumero(jtfNumero.getText());
            obj.setBairro(jtfBairro.getText());
            obj.setCidade(jtfCidade.getText());
            obj.setEstado(estados.get(jcbEstado.getSelectedIndex()));

            //if (obj.getId() == 0) {
            try {
                dao.salvar(obj);
                JOptionPane.showMessageDialog(this, "Cliente " + pr + " Com Sucesso.! ");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao inserir Cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                //System.out.println(" Cliente:" + venda.getCliente().getCodigo() + " - data:" + venda.getDataVenda() + " - Venda: " + venda.getId());
                return;
            }
            // } else {
//                try {
//                    dao.alterar(cli);
//                } catch (Exception ex) {
//                    JOptionPane.showMessageDialog(this, "Erro ao alterar a Nota.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
//                    return;
//                }
            //}
            habilitarFormulario(false);
            if (VendaView.add == "on") {
                dispose();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void habilitarFormulario(boolean ativo) {
        btnNovo.setEnabled(!ativo);
        btnSalvar.setEnabled(ativo);
        //btFinalizar.setEnabled(ativo);
        //btExcluir.setEnabled(ativo);
        //btCancelar.setEnabled(ativo);
        jtfNome.setEnabled(ativo);
        jtfTelefone.setEnabled(ativo);
        jtfRua.setEnabled(ativo);
        jtfNumero.setEnabled(ativo);
        jtfBairro.setEnabled(ativo);
        jtfCidade.setEnabled(ativo);
        jcbEstado.setEnabled(ativo);
        chkSituacao.setEnabled(ativo);
        chkSituacao.setSelected(ativo);
        rbtFisica.setEnabled(ativo);
        rbtJuridica.setEnabled(ativo);
        bgTipo.clearSelection();
        jtfCpf.setEnabled(ativo);
        jtfCnpj.setEnabled(ativo);
        jtfRazaoSocial.setEnabled(ativo);
        //btRemoverItem.setEnabled(ativo);
        //tbGradeItens.setEnabled(!ativo);
        if (!ativo) {
            limpaFormulario();
        }
    }

    private void limpaFormulario() {
        obj = null;
        jtfCodigo.setText(null);
        jtfNome.setText(null);
        jtfDataCadastro.setText(null);
        jtfTelefone.setText("");
        jtfRua.setText("");
        jtfNumero.setText("");
        jtfBairro.setText("");
        jtfCidade.setText("");
        jcbEstado.setSelectedItem(null);
        //this.cidades = new ArrayList<>();
        //ftfValorTotal.setValue(new Double(0));
        //ftfValorUnitario.setValue(new Double(0));
    }

    public List<Estado> getEstados() throws Exception {
        try {
            if ((estados == null) || (estados.size()) == 0) {
                estados = estadoDAO.buscarEstado();
            }
        } catch (Exception e) {
            e.getMessage();
        }
        return estados;
    }

//    public void buscaCidade() {
//       cidadeDAO = new CidadeDAO();
//       cidades = cidadeDAO.buscarCidade(estado);
//    }
    private boolean validaCampos() {
        if (!(jtfNome.getText().length() > 0 && jtfNome.getText() != null)) {
            JOptionPane.showMessageDialog(null, "Campo NOME Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            jtfNome.requestFocus();
            return false;
        }
        if (!(jtfCidade.getText().length() > 0 && jtfCidade.getText() != null)) {
            JOptionPane.showMessageDialog(null, "Campo CIDADE Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            jtfCidade.requestFocus();
            return false;
        }
        if (!(jcbEstado.getSelectedItem() != null)) {
            JOptionPane.showMessageDialog(null, "Campo ESTADO Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            jcbEstado.requestFocus();
            return false;
        }
        if (!(rbtFisica.isSelected() || rbtJuridica.isSelected())) {
            JOptionPane.showMessageDialog(null, "Campo TIPO Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            rbtFisica.requestFocus();
            return false;
        }
        return true;
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarFormulario(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscaCliente obj = new BuscaCliente(this);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbtFisicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtFisicaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfTelefone.setEnabled(true);
            jtfTelefone.requestFocus();
        }
    }//GEN-LAST:event_rbtFisicaKeyPressed

    private void rbtJuridicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtJuridicaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfTelefone.setEnabled(true);
            jtfTelefone.requestFocus();
        }
    }//GEN-LAST:event_rbtJuridicaKeyPressed

    private void jcbEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbEstadoMouseClicked

    }//GEN-LAST:event_jcbEstadoMouseClicked

    private void jcbEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbEstadoFocusLost
        //buscaCidade();
    }//GEN-LAST:event_jcbEstadoFocusLost

    private void rbtFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtFisicaMouseClicked
        jtfCpf.setEnabled(true);
        jtfCnpj.setEnabled(false);
        jtfRazaoSocial.setEnabled(false);
    }//GEN-LAST:event_rbtFisicaMouseClicked

    private void rbtJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtJuridicaMouseClicked
        jtfCnpj.setEnabled(true);
        jtfCpf.setEnabled(false);
        jtfRazaoSocial.setEnabled(true);
    }//GEN-LAST:event_rbtJuridicaMouseClicked

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        jtfNome.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                toUpper(jtfNome);
            }

            public void toUpper(JTextField jt) {
                String s = jt.getText().toUpperCase();
                jt.setText(s);
            }
        });
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jtfCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidadeKeyPressed
        jtfNome.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                toUpper(jtfNome);
            }

            public void toUpper(JTextField jt) {
                String s = jt.getText().toUpperCase();
                jt.setText(s);
            }
        });
    }//GEN-LAST:event_jtfCidadeKeyPressed

    public void setCliente(Cliente cli) {
        Date data = cli.getDataCadastro();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = dateFormat.format(data);

        obj = new Cliente();
        habilitarFormulario(true);
        jtfCodigo.setValue(cli.getId());
        jtfNome.setText(cli.getNome());
        jtfDataCadastro.setText(dataFormatada);
        jtfTelefone.setText(cli.getTelefone());
        jtfRua.setText(cli.getRua());
        jtfNumero.setText(cli.getNumero());
        jtfBairro.setText(cli.getBairro());
        jtfCidade.setText(cli.getCidade());
        combo();
        jcbEstado.setSelectedItem(cli.getEstado().getNome());

        if (cli.getTipo().equals("F")) {
            rbtFisica.setSelected(true);
            jtfCpf.setEnabled(true);
        } else if (cli.getTipo().equals("J")) {
            rbtJuridica.setSelected(true);
            jtfCnpj.setEnabled(true);
            jtfRazaoSocial.setEnabled(true);
        }
        //jcbUnidade.setSelectedItem(produto.getUnidade().getSigla());
        pr = "Alterado";
    }

    private void combo() {
        estadoDAO = new EstadoDAO();

        estados = estadoDAO.buscarEstado();
        jcbEstado.removeAllItems();
        for (Estado ma : estados) {
            jcbEstado.addItem(ma.getNome());
        }
        jcbEstado.setSelectedIndex(-1);

    }

//    private void comboCidade() {
//        cidadeDAO = new CidadeDAO();
//
//        cidades = cidadeDAO.buscarCidade(estado);
//        System.out.println("view.ClienteView.comboCidade()"+estado);
//        jcbCidade.removeAllItems();
//        for (Cidade ma : cidades) {
//            jcbCidade.addItem(ma.getNome());
//        }
//        jcbCidade.setSelectedIndex(-1);
//    }
//    public void buscaCidade() {
//        cidadeDAO = new CidadeDAO();
//        cidades = cidadeDAO.buscarCidade(estado);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnNovo;
    public static javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkSituacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JFormattedTextField jtfCnpj;
    private javax.swing.JFormattedTextField jtfCodigo;
    private javax.swing.JFormattedTextField jtfCpf;
    private javax.swing.JFormattedTextField jtfDataCadastro;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JFormattedTextField jtfRazaoSocial;
    private javax.swing.JTextField jtfRua;
    private javax.swing.JTextField jtfTelefone;
    private javax.swing.JRadioButton rbtFisica;
    private javax.swing.JRadioButton rbtJuridica;
    // End of variables declaration//GEN-END:variables
}
