/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cadastro;

import dao.EstadoDAO;
import dao.FornecedorDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.InternalFrameEvent;
import model.Estado;
import model.Fornecedor;
import view.pesquisa.BuscaFornecedor;

/**
 *
 * @author Celso
 */
public class FornecedorView extends javax.swing.JInternalFrame {

    public static String pr = "";
    private Fornecedor obj = null;
    private FornecedorDAO dao = new FornecedorDAO();

    //FornecedorDAO mDAO;
    private List<Estado> estados;

    private EstadoDAO estadoDAO;

    /**
     * Creates new form FornecedorView
     */
    public FornecedorView() {
        initComponents();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            @Override
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                dispose();
                Menu.menuFornecedor.setEnabled(true);
            }

            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbtJuridica = new javax.swing.JRadioButton();
        rbtFisica = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox();
        jtfEmail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtfSite = new javax.swing.JTextField();
        jtfContato = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtfContato_tel = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JFormattedTextField();
        ftfFornecedor = new javax.swing.JFormattedTextField();
        jtfCnpj = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("FORNECEDORES");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Fornecedores"));

        jLabel1.setText("CÓDIGO.:");

        jLabel2.setText("NOME.:");

        bgTipo.add(rbtJuridica);
        rbtJuridica.setText("Jurídica");
        rbtJuridica.setEnabled(false);
        rbtJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtJuridicaMouseClicked(evt);
            }
        });
        rbtJuridica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtJuridicaKeyPressed(evt);
            }
        });

        bgTipo.add(rbtFisica);
        rbtFisica.setText("Fisica");
        rbtFisica.setEnabled(false);
        rbtFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtFisicaMouseClicked(evt);
            }
        });
        rbtFisica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtFisicaKeyPressed(evt);
            }
        });

        jLabel12.setText("TIPO.:");

        try {
            jtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfTelefone.setEnabled(false);
        jtfTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTelefoneKeyPressed(evt);
            }
        });

        jLabel3.setText("TELEFONE.:");

        jLabel8.setText("ENDEREÇO.:");

        jtfEndereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfEndereco.setEnabled(false);
        jtfEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfEnderecoKeyPressed(evt);
            }
        });

        jLabel10.setText("BAIRRO.:");

        jtfBairro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfBairro.setEnabled(false);
        jtfBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfBairroKeyPressed(evt);
            }
        });

        jLabel9.setText("CIDADE.:");

        jtfCidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCidade.setEnabled(false);
        jtfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCidadeKeyPressed(evt);
            }
        });

        jLabel11.setText("ESTADO.:");

        jcbEstado.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));
        jcbEstado.setEnabled(false);
        jcbEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbEstadoKeyPressed(evt);
            }
        });

        jtfEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfEmail.setEnabled(false);
        jtfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfEmailKeyPressed(evt);
            }
        });

        jLabel16.setText("E-MAIL.:");

        jLabel17.setText("SITE.:");

        jtfSite.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfSite.setEnabled(false);
        jtfSite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSiteKeyPressed(evt);
            }
        });

        jtfContato.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfContato.setEnabled(false);
        jtfContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContatoKeyPressed(evt);
            }
        });

        jLabel18.setText("CONTATO.:");

        jLabel19.setText("TEL CONTATO.:");

        try {
            jtfContato_tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfContato_tel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfContato_tel.setEnabled(false);
        jtfContato_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContato_telKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Zoom.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCodigo.setEnabled(false);

        ftfFornecedor.setEnabled(false);
        ftfFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfFornecedorKeyPressed(evt);
            }
        });

        try {
            jtfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCnpj.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCnpj.setEnabled(false);
        jtfCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCnpjKeyPressed(evt);
            }
        });

        jLabel20.setText("CNPJ.:");

        try {
            jtfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCpf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCpf.setEnabled(false);
        jtfCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCpfKeyPressed(evt);
            }
        });

        jLabel21.setText("CPF.:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfTelefone)
                            .addComponent(jtfBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jtfCidade, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jtfEndereco)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 62, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jtfCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbtFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtJuridica))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmail)
                            .addComponent(jtfContato)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19)
                                .addComponent(jtfSite)
                                .addComponent(jtfContato_tel, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jtfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtFisica)
                            .addComponent(rbtJuridica)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfContato_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jtfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Pessoais", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Histórico", jPanel4);

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Novo");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNovo.setMaximumSize(new java.awt.Dimension(92, 35));
        btnNovo.setPreferredSize(new java.awt.Dimension(70, 35));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvar.setMaximumSize(new java.awt.Dimension(92, 35));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.setMaximumSize(new java.awt.Dimension(92, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jTabbedPane5)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtJuridicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtJuridicaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfTelefone.setEnabled(true);
            jtfTelefone.requestFocus();
        }
    }//GEN-LAST:event_rbtJuridicaKeyPressed

    private void rbtFisicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtFisicaKeyPressed
        if (rbtFisica.isSelected()) {
            jtfCpf.setEnabled(true);
            //jtfTelefone.setEnabled(true);
            //jtfTelefone.requestFocus();
        }
    }//GEN-LAST:event_rbtFisicaKeyPressed

    private void jtfContatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContatoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContatoKeyPressed

    private void jtfSiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSiteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSiteKeyPressed

    private void jtfEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEmailKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfSite.setEnabled(true);
            jtfSite.requestFocus();
        }
    }//GEN-LAST:event_jtfEmailKeyPressed

    private void jcbEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbEstadoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfEmail.setEnabled(true);
            jtfEmail.requestFocus();
        }
    }//GEN-LAST:event_jcbEstadoKeyPressed

    private void jtfCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidadeKeyPressed
          jtfCidade.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                toUpper(jtfCidade);
            }

            public void toUpper(JTextField jt) {
                String s = jt.getText().toUpperCase();
                jt.setText(s);
            }
        });
    }//GEN-LAST:event_jtfCidadeKeyPressed

    private void jtfBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBairroKeyPressed
        jtfBairro.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                toUpper(jtfBairro);
            }

            public void toUpper(JTextField jt) {
                String s = jt.getText().toUpperCase();
                jt.setText(s);
            }
        });
    }//GEN-LAST:event_jtfBairroKeyPressed

    private void jtfEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEnderecoKeyPressed
        jtfEndereco.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                toUpper(jtfEndereco);
            }

            public void toUpper(JTextField jt) {
                String s = jt.getText().toUpperCase();
                jt.setText(s);
            }
        });
    }//GEN-LAST:event_jtfEnderecoKeyPressed

    private void jtfTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTelefoneKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfEndereco.setEnabled(true);
            jtfEndereco.requestFocusInWindow();
        }
    }//GEN-LAST:event_jtfTelefoneKeyPressed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        obj = new Fornecedor();
        ftfFornecedor.requestFocus();
        habilitarFormulario(true);
        combo();
        pr = "Cadastrado";
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (validaCampos()) {
            if (!jtfCodigo.getText().equals("")) {
                obj.setId(Long.parseLong(jtfCodigo.getText()));
            }
            obj.setEmpresa(LoginView.emp);
            if (rbtFisica.isSelected()) {
                obj.setTipo("F");
            } else if (rbtJuridica.isSelected()) {
                obj.setTipo("J");
            }
            obj.setNome(ftfFornecedor.getText());
            obj.setTelefone(jtfTelefone.getText());
            obj.setEndereco(jtfEndereco.getText());
            obj.setBairro(jtfBairro.getText());
            obj.setCidade(jtfCidade.getText());
            obj.setEstado(estados.get(jcbEstado.getSelectedIndex()));
            obj.setEmail(jtfEmail.getText());
            obj.setSite(jtfSite.getText());
            obj.setContato(jtfContato.getText());
            obj.setContatotelefone(jtfContato_tel.getText());

            try {
                dao.salvar(obj);
                JOptionPane.showMessageDialog(this, "Fornecedor " + pr + " Com Sucesso.! ");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao inserir Fornecedor.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                //System.out.println(" Cliente:" + venda.getCliente().getCodigo() + " - data:" + venda.getDataVenda() + " - Venda: " + venda.getId());
                return;
            }
            //  } else {
            //                try {
            //                    dao.alterar(cli);
            //                } catch (Exception ex) {
            //                    JOptionPane.showMessageDialog(this, "Erro ao alterar a Nota.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            //                    return;
            //                }
            //  }
            habilitarFormulario(false);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarFormulario(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtfContato_telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContato_telKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContato_telKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscaFornecedor busca = new BuscaFornecedor(this);
        busca.setLocationRelativeTo(null);
        busca.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCnpjKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCnpjKeyPressed

    private void jtfCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCpfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCpfKeyPressed

    private void rbtFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtFisicaMouseClicked
        jtfCpf.setEnabled(true);
        jtfCnpj.setEnabled(false);
    }//GEN-LAST:event_rbtFisicaMouseClicked

    private void rbtJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtJuridicaMouseClicked
        jtfCnpj.setEnabled(true);
        jtfCpf.setEnabled(false);
    }//GEN-LAST:event_rbtJuridicaMouseClicked

    private void ftfFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfFornecedorKeyPressed
        ftfFornecedor.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                toUpper(ftfFornecedor);
            }

            public void toUpper(JTextField jt) {
                String s = jt.getText().toUpperCase();
                jt.setText(s);
            }
        });
    }//GEN-LAST:event_ftfFornecedorKeyPressed

    public void setFornecedor(Fornecedor e) {
        obj = new Fornecedor();
        habilitarFormulario(true);
        jtfCodigo.setValue(e.getId());
        ftfFornecedor.setValue(e);
        if (e.getTipo().equals("F")) {
            rbtFisica.setSelected(true);
        } else if (e.getTipo().equals("J")) {
            rbtJuridica.setSelected(true);
        }
        jtfTelefone.setText(e.getTelefone());
        jtfEndereco.setText(e.getEndereco());
        jtfBairro.setText(e.getBairro());
        jtfCidade.setText(e.getCidade());
        combo();
        jcbEstado.setSelectedItem(e.getEstado().getNome());
        jtfEmail.setText(e.getEmail());
        jtfSite.setText(e.getSite());
        jtfContato.setText(e.getContato());
        jtfContato_tel.setText(e.getContatotelefone());
        pr = "Alterado";
    }

    private void combo() {
        estadoDAO = new EstadoDAO();

        estados = estadoDAO.buscarEstado();
        jcbEstado.removeAllItems();
        for (Estado ma : estados) {
            jcbEstado.addItem(ma.getNome());
        }
        jcbEstado.setSelectedIndex(-1);
    }

    private void habilitarFormulario(boolean ativo) {
        ftfFornecedor.setEnabled(ativo);
        jtfTelefone.setEnabled(ativo);
        jtfEndereco.setEnabled(ativo);
        jtfBairro.setEnabled(ativo);
        jtfCidade.setEnabled(ativo);
        jcbEstado.setEnabled(ativo);
        jtfEmail.setEnabled(ativo);
        jtfSite.setEnabled(ativo);
        jtfContato.setEnabled(ativo);
        jtfContato_tel.setEnabled(ativo);
        rbtFisica.setEnabled(ativo);
        rbtJuridica.setEnabled(ativo);
        bgTipo.clearSelection();
        btnNovo.setEnabled(!ativo);
        btnSalvar.setEnabled(ativo);
        jtfCpf.setEnabled(ativo);
        jtfCnpj.setEnabled(ativo);
        //btRemoverItem.setEnabled(ativo);
        //tbGradeItens.setEnabled(!ativo);
        if (!ativo) {
            limpaFormulario();
        }
    }

    private void limpaFormulario() {
        obj = null;
        jtfCodigo.setText(null);
        ftfFornecedor.setText(null);
        jtfTelefone.setText(null);
        jtfEndereco.setText(null);
        jtfBairro.setText(null);
        jtfCidade.setText(null);
        jcbEstado.setSelectedItem(null);
        jtfEmail.setText(null);
        jtfSite.setText(null);
        jtfContato.setText(null);
        jtfContato_tel.setText(null);
    }

    private boolean validaCampos() {
        if (!(ftfFornecedor.getText().length() > 0 && ftfFornecedor.getText() != null)) {
            JOptionPane.showMessageDialog(null, "Campo NOME Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            ftfFornecedor.requestFocus();
            return false;
        }
        if (!(rbtFisica.isSelected() || rbtJuridica.isSelected())) {
            JOptionPane.showMessageDialog(null, "Campo TIPO Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            rbtFisica.requestFocus();
            return false;
        }
        if (!(jtfCidade.getText().length() > 0 && jtfCidade.getText() != null)) {
            JOptionPane.showMessageDialog(null, "Campo CIDADE Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            jtfCidade.requestFocus();
            return false;
        }
        if (!(jcbEstado.getSelectedItem() != null)) {
            JOptionPane.showMessageDialog(null, "Campo ESTADO Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            jcbEstado.requestFocus();
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnNovo;
    public static javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField ftfFornecedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox jcbEstado;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JFormattedTextField jtfCnpj;
    private javax.swing.JFormattedTextField jtfCodigo;
    private javax.swing.JTextField jtfContato;
    private javax.swing.JFormattedTextField jtfContato_tel;
    private javax.swing.JFormattedTextField jtfCpf;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfSite;
    private javax.swing.JFormattedTextField jtfTelefone;
    private javax.swing.JRadioButton rbtFisica;
    private javax.swing.JRadioButton rbtJuridica;
    // End of variables declaration//GEN-END:variables
}
