package view.cadastro;

import dao.Generico;
import dao.GenericoDAO;
import dao.UnidadeDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableCellRenderer;
import model.EntidadeBase;
import model.Unidade;
import static view.cadastro.LoginView.emp;
import view.tm.UnidadeTableModel;

/**
 * @author Celso
 */
public class UnidadeView extends javax.swing.JInternalFrame {

    private Unidade obj = null;
    private UnidadeDAO dao = new UnidadeDAO();

    /**
     * Creates new form UnidadeView
     */
    public UnidadeView() {
        initComponents();
        carregarGrade();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            @Override
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                dispose();
                Menu.menuUnidade.setEnabled(true);
                //Menu.btnCliente.setEnabled(true);
            }

            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfSigla = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGrade = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("UNIDADES DE MEDIDAS");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Unidade de Medida"));

        jLabel2.setText("CÓDIGO.:");

        jtfCodigo.setEnabled(false);

        jLabel1.setText("DESCRIÇÃO.:");

        jtfNome.setEnabled(false);
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Novo");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNovo.setMaximumSize(new java.awt.Dimension(92, 35));
        btnNovo.setPreferredSize(new java.awt.Dimension(70, 35));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvar.setMaximumSize(new java.awt.Dimension(92, 35));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.setMaximumSize(new java.awt.Dimension(92, 35));
        jToolBar1.add(btnCancelar);

        jLabel3.setText("SIGLA.:");

        jtfSigla.setEnabled(false);
        jtfSigla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSiglaKeyPressed(evt);
            }
        });

        tbGrade.setModel(new UnidadeTableModel());
        jScrollPane1.setViewportView(tbGrade);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfNome)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfSigla, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        obj = new Unidade();
        jtfSigla.requestFocus();
        habilitarFormulario(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (validaCampos()) {
            if (!jtfCodigo.getText().equals("")) {
                obj.setId(Long.parseLong(jtfCodigo.getText()));
            }
            obj.setEmpresa(emp);
            obj.setNome(jtfNome.getText());
            obj.setSigla(jtfSigla.getText());
            try {
                dao.salvar(obj);
                JOptionPane.showMessageDialog(this, "Unidade de Medida Cadastrada ! ");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao inserir a Unidade.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            habilitarFormulario(false);
            carregarGrade();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        jtfNome.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                toUpper(jtfNome);
            }

            public void toUpper(JTextField jt) {
                String s = jt.getText().toUpperCase();
                jt.setText(s);
            }
        });
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jtfSiglaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSiglaKeyPressed
        jtfSigla.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                toUpper(jtfSigla);
            }

            public void toUpper(JTextField jt) {
                String s = jt.getText().toUpperCase();
                jt.setText(s);
            }
        });
    }//GEN-LAST:event_jtfSiglaKeyPressed

    private void habilitarFormulario(boolean ativo) {
        btnNovo.setEnabled(!ativo);
        btnSalvar.setEnabled(ativo);
        jtfNome.setEnabled(ativo);
        jtfSigla.setEnabled(ativo);
        //btExcluir.setEnabled(ativo);
        //btCancelar.setEnabled(ativo);
        if (!ativo) {
            limpaFormulario();
        }
    }

    private void limpaFormulario() {
        obj = null;
        jtfCodigo.setText(null);
        jtfNome.setText(null);
        jtfSigla.setText(null);
    }

    private boolean validaCampos() {
        if (!(jtfSigla.getText().length() > 0 && jtfSigla.getText() != null)) {
            JOptionPane.showMessageDialog(null, "Campo SIGLA Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            jtfSigla.requestFocus();
            return false;
        }
        if (!(jtfNome.getText().length() > 0 && jtfNome.getText() != null)) {
            JOptionPane.showMessageDialog(null, "Campo DESCRIÇÃO Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            jtfNome.requestFocus();
            return false;
        }
        return true;
    }

    private void carregarGrade() {

        //Generico gDAO = new Generico();
        UnidadeTableModel tm = (UnidadeTableModel) tbGrade.getModel();
        try {
            tm.setDados(dao.listarTodos(emp.getId()));

            DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            DefaultTableCellRenderer direita = new DefaultTableCellRenderer();

            esquerda.setHorizontalAlignment(SwingConstants.LEFT);
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            direita.setHorizontalAlignment(SwingConstants.RIGHT);

            tbGrade.getColumnModel().getColumn(0).setCellRenderer(direita);
            tbGrade.getColumnModel().getColumn(1).setCellRenderer(esquerda);
            tbGrade.getColumnModel().getColumn(2).setCellRenderer(centralizado);

            tbGrade.getColumnModel().getColumn(0).setPreferredWidth(60);
            tbGrade.getColumnModel().getColumn(1).setPreferredWidth(250);
            tbGrade.getColumnModel().getColumn(2).setPreferredWidth(30);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grade.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnNovo;
    public static javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfSigla;
    private javax.swing.JTable tbGrade;
    // End of variables declaration//GEN-END:variables
}
