package view.movimento;

import dao.EntradaDAO;
import dao.EstadoDAO;
import dao.ProdutoDAO;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableCellRenderer;
import model.Entrada;
import model.EntradaItem;
import model.Estado;
import model.Fornecedor;
import model.Produto;
import model.enuns.Situacao;
import view.cadastro.FornecedorView;
import static view.cadastro.LoginView.emp;
import view.cadastro.Menu;
import static view.cadastro.Menu.menuFornecedor;
import view.pesquisa.BuscaFornecedor;
import view.tm.EntradaItemTableModel;
import view.tm.EntradaTableModel;

/**
 *
 * @author Celso
 */
public class EntradaView extends javax.swing.JInternalFrame {

    public static String add;
    public static String pr = "";
    public static Entrada obj = null;
    private EntradaDAO objDAO = new EntradaDAO();

    private List<Estado> estados;
    EstadoDAO estadoDAO;

    /**
     * Creates new form EntradaView
     */
    public EntradaView() {
        initComponents();
        
        infos();
        carregarGrade();

        UIManager.put("ComboBox.disabledForeground", Color.BLACK);

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            @Override
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                dispose();
                Menu.menuEntrada.setEnabled(true);
            }

            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ftfOperacao = new javax.swing.JTextField();
        jtfCodFornecedor = new javax.swing.JFormattedTextField();
        jtfCidade = new javax.swing.JFormattedTextField();
        jtfCodProduto = new javax.swing.JFormattedTextField();
        ftfProdutoEntrada = new javax.swing.JFormattedTextField();
        btProduto = new javax.swing.JButton();
        ftfQuantidadeEntrada = new javax.swing.JFormattedTextField();
        ftfValorUnitarioEntrada = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btCliente = new javax.swing.JButton();
        ftfFornecedor = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfDataEmissao = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        abasVenda = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGradeItens = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbGrade = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        ftfSubTotal = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        ftfDesconto = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        ftfVlrTotal = new javax.swing.JFormattedTextField();
        jToolBar2 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btFinalizar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jtfDataEntrada = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfSerie = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcbUf = new javax.swing.JComboBox<>();
        jtfFrete = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        ftfCodEmpresa = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        btAddFornecedor = new javax.swing.JButton();
        ftfEmpresa = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("ENTRADA DE MERCADORIA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da Nota Fiscal de Entrada"));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("NATUREZA DA OPERAÇÃO.:");

        ftfOperacao.setEditable(false);
        ftfOperacao.setEnabled(false);

        jtfCodFornecedor.setEditable(false);
        jtfCodFornecedor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCodFornecedor.setEnabled(false);

        jtfCidade.setEditable(false);
        jtfCidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCidade.setEnabled(false);
        jtfCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCidadeActionPerformed(evt);
            }
        });

        jtfCodProduto.setEditable(false);
        jtfCodProduto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCodProduto.setEnabled(false);

        ftfProdutoEntrada.setEditable(false);

        btProduto.setToolTipText("Localizar cliente");
        btProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btProduto.setEnabled(false);
        btProduto.setPreferredSize(new java.awt.Dimension(21, 21));
        btProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutoActionPerformed(evt);
            }
        });

        ftfQuantidadeEntrada.setEnabled(false);

        ftfValorUnitarioEntrada.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("R$ UNITÁRIO.:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("QUANTIDADE.:");

        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Zoom.png"))); // NOI18N
        btCliente.setToolTipText("Localizar cliente");
        btCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btCliente.setEnabled(false);
        btCliente.setPreferredSize(new java.awt.Dimension(21, 21));
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        ftfFornecedor.setEditable(false);
        ftfFornecedor.setColumns(25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("FORNECEDOR.:");

        jtfDataEmissao.setEditable(false);
        jtfDataEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jtfDataEmissao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfDataEmissao.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("EMISSÃO.:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("PRODUTO.:");

        tbGradeItens.setModel(new EntradaItemTableModel());
        jScrollPane1.setViewportView(tbGradeItens);

        abasVenda.addTab("PRODUTOS", jScrollPane1);

        tbGrade.setModel(new EntradaTableModel());
        tbGrade.setCellSelectionEnabled(true);
        tbGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGradeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbGrade);
        tbGrade.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        abasVenda.addTab("NOTAS", jScrollPane3);

        jLabel9.setText("TOTAL DOS PRODUTOS.:");

        ftfSubTotal.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        ftfSubTotal.setEnabled(false);
        ftfSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setText("R$ DESCONTO.:");

        ftfDesconto.setEnabled(false);

        jLabel1.setText("NOTA + FRETE.:");

        ftfVlrTotal.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        ftfVlrTotal.setEnabled(false);
        ftfVlrTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setRollover(true);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.setToolTipText("Nova Venda");
        btNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btNovo.setMaximumSize(new java.awt.Dimension(92, 35));
        btNovo.setPreferredSize(new java.awt.Dimension(70, 35));
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        btNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btNovoKeyPressed(evt);
            }
        });
        jToolBar2.add(btNovo);

        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/finalizar.png"))); // NOI18N
        btFinalizar.setText("Finalizar");
        btFinalizar.setEnabled(false);
        btFinalizar.setFocusable(false);
        btFinalizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btFinalizar.setMaximumSize(new java.awt.Dimension(92, 35));
        btFinalizar.setPreferredSize(new java.awt.Dimension(80, 41));
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });
        jToolBar2.add(btFinalizar);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("Cancelar Venda");
        btCancelar.setEnabled(false);
        btCancelar.setFocusable(false);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btCancelar.setMaximumSize(new java.awt.Dimension(92, 35));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jToolBar2.add(btCancelar);

        jtfDataEntrada.setEditable(false);
        jtfDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/y"))));
        jtfDataEntrada.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel10.setText("UF.:");

        jtfNumero.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfNumero.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setText("NUMERO DA NF.:");

        jtfSerie.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfSerie.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setText("SERIE");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel13.setText("ENTRADA.:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setText("CIDADE.:");

        jcbUf.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jcbUf.setEnabled(false);

        jtfFrete.setEnabled(false);
        jtfFrete.setValue(new Double(0));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel15.setText("R$ FRETE.:");

        ftfCodEmpresa.setEditable(false);
        ftfCodEmpresa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ftfCodEmpresa.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel16.setText("EMPRESA.:");

        btAddFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        btAddFornecedor.setToolTipText("Localizar cliente");
        btAddFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAddFornecedor.setEnabled(false);
        btAddFornecedor.setPreferredSize(new java.awt.Dimension(21, 21));
        btAddFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddFornecedorActionPerformed(evt);
            }
        });

        ftfEmpresa.setEditable(false);
        ftfEmpresa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ftfEmpresa.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abasVenda)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfVlrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfCodFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(ftfCodEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jtfCodProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jtfFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCidade)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(56, 56, 56))
                            .addComponent(jcbUf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 146, Short.MAX_VALUE))
                            .addComponent(ftfEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtfDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ftfProdutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfQuantidadeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfValorUnitarioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfCodEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ftfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfCodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btAddFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ftfValorUnitarioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ftfQuantidadeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ftfProdutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))
                        .addComponent(abasVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfVlrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(btProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCidadeActionPerformed

    private void btProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutoActionPerformed
        ProdutoEntrada busca = new ProdutoEntrada(this);
        busca.setLocationRelativeTo(null);
        busca.setVisible(true);
    }//GEN-LAST:event_btProdutoActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        BuscaFornecedor busca = new BuscaFornecedor(this);
        busca.setLocationRelativeTo(null);
        busca.setVisible(true);
    }//GEN-LAST:event_btClienteActionPerformed

    private void tbGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGradeMouseClicked
        if (evt.getClickCount() == 2) {
            abasVenda.setSelectedIndex(0);
            int linhaSelecionada = tbGrade.getSelectedRow();
            EntradaTableModel vtm = (EntradaTableModel) tbGrade.getModel();
            obj = vtm.getRowValue(linhaSelecionada);

            jtfCodFornecedor.setValue(obj.getFornecedor().getId());
            ftfFornecedor.setValue(obj.getFornecedor());
            jtfDataEntrada.setValue(obj.getDataentrada());
            jtfDataEmissao.setValue(obj.getDataemissao());
            ftfSubTotal.setValue(obj.getVlrTotal());

            EntradaItemTableModel ivtm = (EntradaItemTableModel) tbGradeItens.getModel();
            ivtm.setDados(obj.getItens());

            DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            DefaultTableCellRenderer direita = new DefaultTableCellRenderer();

            esquerda.setHorizontalAlignment(SwingConstants.LEFT);
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            direita.setHorizontalAlignment(SwingConstants.RIGHT);

            tbGradeItens.getColumnModel().getColumn(0).setCellRenderer(direita);
            tbGradeItens.getColumnModel().getColumn(1).setCellRenderer(esquerda);
            tbGradeItens.getColumnModel().getColumn(2).setCellRenderer(centralizado);
            tbGradeItens.getColumnModel().getColumn(3).setCellRenderer(direita);
            tbGradeItens.getColumnModel().getColumn(4).setCellRenderer(direita);

            tbGradeItens.getColumnModel().getColumn(0).setPreferredWidth(15);
            tbGradeItens.getColumnModel().getColumn(1).setPreferredWidth(290);
            tbGradeItens.getColumnModel().getColumn(2).setPreferredWidth(30);
            tbGradeItens.getColumnModel().getColumn(3).setPreferredWidth(35);
            tbGradeItens.getColumnModel().getColumn(4).setPreferredWidth(35);
            habilitarFormulario(true);
        }
    }//GEN-LAST:event_tbGradeMouseClicked

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        abasVenda.setSelectedIndex(0);
        obj = new Entrada();
        jtfDataEntrada.setValue(new Date());
        jtfDataEmissao.setValue(new Date());
        habilitarFormulario(true);
        combo();
    }//GEN-LAST:event_btNovoActionPerformed

    private void combo() {
        estadoDAO = new EstadoDAO();

        estados = estadoDAO.buscarEstado();
        jcbUf.removeAllItems();
        for (Estado ma : estados) {
            jcbUf.addItem(ma.getNome());
        }
        jcbUf.setSelectedIndex(-1);

    }

    private void btNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btNovoKeyPressed

    }//GEN-LAST:event_btNovoKeyPressed

    public void salvar(boolean finalizar) {
        if (validarFormulario()) {
            obj.setEmpresa(emp);
            obj.setDataentrada((Date) jtfDataEntrada.getValue());
            obj.setDataemissao((Date) jtfDataEmissao.getValue());
            obj.setFornecedor((Fornecedor) ftfFornecedor.getValue());
            obj.setNumero(Integer.parseInt(jtfNumero.getText()));
            obj.setSerie(jtfSerie.getText());
            obj.setVlrfrete((Double) jtfFrete.getValue());
            if (finalizar) {
                obj.setSituacao(Situacao.FINALIZADA);
            } else {
                obj.setSituacao(Situacao.ABERTA);
            }

            //if (venda.getId() == 0) {
            try {
                objDAO.salvar(obj);
                System.out.println(" Cliente:" + obj.getFornecedor().getId() + " - data:" + obj.getDataentrada() + " - Venda:" + obj.getId() + " Situacao.:" + obj.getSituacao());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao inserir a Entrada.!\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                System.out.println(" Fornecedor: " + obj.getFornecedor().getId() + " - data: " + obj.getDataentrada() + " - Entrada: " + obj.getId());
                return;
            }
//            } else {
//                try {
//                    //vendaDAO.alterar(venda);
//                    if (JOptionPane.showConfirmDialog(null, "Imprimir Venda? ", "Pergunta!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
//                        //imprimirVenda(venda);
//                    } else {
//                    }
//                } catch (Exception ex) {
//                    JOptionPane.showMessageDialog(this, "Erro ao alterar a venda.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
//                    return;
//                }
//            }
            habilitarFormulario(false);
            carregarGrade();
        }
    }

    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Finalizar a Entrada de Mercadoria?");
//        if (opcao == 0) {
//            ProdutoDAO produtoDAO = new ProdutoDAO();
//            for (EntradaItem iv : obj.getItens()) {
//                try {
//                    if (iv.getQuantidade() > produtoDAO.recuperar((long) iv.getProduto().getId()).getQuantidade()) {
//                        JOptionPane.showMessageDialog(this, "Impossível finalizar.\nProduto " + iv.getProduto() + " em falta no estoque.", "Alerta", JOptionPane.WARNING_MESSAGE);
//                        return;
//                    }
//                } catch (Exception ex) {
//                    JOptionPane.showMessageDialog(this, "Erro ao consultar o estoque.", "Erro", JOptionPane.ERROR_MESSAGE);
//                    return;
//                }
//            }
//            salvar(true);
//        }
        salvar(true);
    }//GEN-LAST:event_btFinalizarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        habilitarFormulario(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAddFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddFornecedorActionPerformed
        FornecedorView form = new FornecedorView();
        Menu.desktopPane.add(form);
        form.setVisible(true);
        form.moveToFront();
        menuFornecedor.setEnabled(false);
        add = "on";
    }//GEN-LAST:event_btAddFornecedorActionPerformed

    private void habilitarFormulario(boolean ativo) {
        jtfDataEntrada.setEnabled(ativo);
        jtfDataEmissao.setEnabled(ativo);
        ftfFornecedor.setEnabled(ativo);
        btCliente.setEnabled(ativo);
        jtfNumero.setEnabled(ativo);
        jtfSerie.setEnabled(ativo);
        jtfFrete.setEnabled(ativo);
        ftfProdutoEntrada.setEnabled(ativo);
        btProduto.setEnabled(ativo);
        ftfQuantidadeEntrada.setEnabled(ativo);
        ftfValorUnitarioEntrada.setEnabled(ativo);
        
        btAddFornecedor.setEnabled(ativo);
        btNovo.setEnabled(!ativo);
        btFinalizar.setEnabled(ativo);
        btCancelar.setEnabled(ativo);
        //btRemoverItem.setEnabled(ativo);
        tbGradeItens.setEnabled(!ativo);

        if (!ativo) {
            limpaFormulario();
        }
    }

    private void limpaFormulario() {
        obj = null;
        jtfDataEntrada.setValue(null);
        jtfDataEmissao.setValue(null);
        jtfCodFornecedor.setText("");
        ftfFornecedor.setText("");
        jtfCidade.setText("");
        jtfNumero.setText("");
        jtfSerie.setText("");
        jtfSerie.setText("");
        jtfFrete.setText("");
        jcbUf.setSelectedItem(null);
        ftfSubTotal.setValue(new Double(0));
        ftfVlrTotal.setValue(new Double(0));
        ftfProdutoEntrada.setValue(null);
        //spQuantidade.setValue(1);
        ftfValorUnitarioEntrada.setValue(new Double(0));
        tbGradeItens.setModel(new EntradaItemTableModel());
        //jcbCondicao.setSelectedItem(null);
        limpaFormularioItens();
    }

    private void limpaFormularioItens() {
        jtfCodProduto.setValue(null);
        ftfProdutoEntrada.setValue(null);
        //spQuantidade.setValue(1);
        ftfQuantidadeEntrada.setValue("1");
        ftfValorUnitarioEntrada.setValue(new Double(0));
    }

    private boolean validarFormulario() {
        if (ftfFornecedor.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Fornecedor Inválido!", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfFornecedor.requestFocus();
            return false;
        }
        if (!(jtfNumero.getText().length() > 0 && jtfNumero.getText() != null)) {
            JOptionPane.showMessageDialog(this, "Número da NF não pode ser em Branco.!", "Alerta", JOptionPane.WARNING_MESSAGE);
            jtfNumero.requestFocus();
            return false;
        }
        if (!(jtfSerie.getText().length() > 0 && jtfSerie.getText() != null)) {
            JOptionPane.showMessageDialog(this, "Série da NF não pode ser em Branco.!", "Alerta", JOptionPane.WARNING_MESSAGE);
            jtfSerie.requestFocus();
            return false;
        }
//        if (obj.quantidadeItens() == 0) {
//            JOptionPane.showMessageDialog(this, "Quantidade de itens inválida.", "Alerta", JOptionPane.WARNING_MESSAGE);
//            //tpConteudo.setSelectedIndex(1);
//            return false;
//        }
        return true;
    }

    private boolean validarFormularioItens() {
        if (ftfProdutoEntrada.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Produto inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfProdutoEntrada.requestFocus();
            return false;
        }
        return true;
    }

    public void setFornecedor(Fornecedor e) {
        habilitarFormulario(true);
        jtfCodFornecedor.setValue(e.getId());
        ftfFornecedor.setValue(e);
        jtfCidade.setText(e.getCidade());
        combo();
        jcbUf.setSelectedItem(e.getEstado().getNome());
    }

    public void setProduto(Produto produto) {
        ftfProdutoEntrada.setValue(produto);
        jtfCodProduto.setValue(produto.getId());
        ftfValorUnitarioEntrada.setValue(produto.getVlrvenda());
    }
    
    private void infos() {
        ftfCodEmpresa.setValue(emp.getId());
        ftfEmpresa.setValue(emp);
    }

    private void carregarGrade() {
        //abasVenda.setSelectedIndex(1);
        EntradaTableModel tm = (EntradaTableModel) tbGrade.getModel();
        try {
            tm.setDados(objDAO.listarTodos());

            DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            DefaultTableCellRenderer direita = new DefaultTableCellRenderer();

            esquerda.setHorizontalAlignment(SwingConstants.LEFT);
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            direita.setHorizontalAlignment(SwingConstants.RIGHT);

            tbGrade.getColumnModel().getColumn(0).setCellRenderer(direita);
            tbGrade.getColumnModel().getColumn(1).setCellRenderer(esquerda);
            tbGrade.getColumnModel().getColumn(2).setCellRenderer(centralizado);
            tbGrade.getColumnModel().getColumn(3).setCellRenderer(direita);
            tbGrade.getColumnModel().getColumn(4).setCellRenderer(centralizado);

            tbGrade.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbGrade.getColumnModel().getColumn(1).setPreferredWidth(240);
            tbGrade.getColumnModel().getColumn(2).setPreferredWidth(30);
            tbGrade.getColumnModel().getColumn(3).setPreferredWidth(30);
            tbGrade.getColumnModel().getColumn(4).setPreferredWidth(30);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grade.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTabbedPane abasVenda;
    private javax.swing.JButton btAddFornecedor;
    public static javax.swing.JButton btCancelar;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btFinalizar;
    public static javax.swing.JButton btNovo;
    private javax.swing.JButton btProduto;
    private javax.swing.JFormattedTextField ftfCodEmpresa;
    private javax.swing.JFormattedTextField ftfDesconto;
    private javax.swing.JFormattedTextField ftfEmpresa;
    private javax.swing.JFormattedTextField ftfFornecedor;
    private javax.swing.JTextField ftfOperacao;
    private javax.swing.JFormattedTextField ftfProdutoEntrada;
    private javax.swing.JFormattedTextField ftfQuantidadeEntrada;
    public static javax.swing.JFormattedTextField ftfSubTotal;
    private javax.swing.JFormattedTextField ftfValorUnitarioEntrada;
    public static javax.swing.JFormattedTextField ftfVlrTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JComboBox<String> jcbUf;
    private javax.swing.JFormattedTextField jtfCidade;
    private javax.swing.JFormattedTextField jtfCodFornecedor;
    private javax.swing.JFormattedTextField jtfCodProduto;
    private javax.swing.JFormattedTextField jtfDataEmissao;
    private javax.swing.JFormattedTextField jtfDataEntrada;
    public static javax.swing.JFormattedTextField jtfFrete;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfSerie;
    private javax.swing.JTable tbGrade;
    public static javax.swing.JTable tbGradeItens;
    // End of variables declaration//GEN-END:variables

}
