package view.movimento;

import dao.ConciliacaoDAO;
import dao.ContaReceberDAO;
import dao.PgFormaDAO;
import dao.ProdutoDAO;
import dao.VendaDAO;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableCellRenderer;
import model.Cliente;
import model.Conciliacao;
import model.PgForma;
import model.Produto;
import model.Venda;
import model.VendaItem;
import model.ContaReceber;
import model.enuns.Situacao;
import view.cadastro.ClienteView;
import static view.cadastro.LoginView.emp;
import view.cadastro.Menu;
import static view.cadastro.Menu.menuCliente;
import view.pesquisa.BuscaCliente;
import view.pesquisa.BuscaProduto;
import view.tm.VendaItemTableModel;
import view.tm.VendaTableModel;

/**
 * @author Celso
 */
public class VendaView extends javax.swing.JInternalFrame {

    public static String add;
    //public static String tb = "";

    private Venda venda = null;
    private VendaDAO vendaDAO = new VendaDAO();
    private final NumberFormat NFC = NumberFormat.getCurrencyInstance();

    List<PgForma> listaForma;
    PgFormaDAO fDAO;

    public VendaView() {
        initComponents();
        infos();
        carregarGrade();
        grade();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            @Override
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                dispose();
                Menu.menuVenda.setEnabled(true);
                //Menu.btnProduto.setEnabled(true);
            }

            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ftfOperacao = new javax.swing.JTextField();
        jtfCodCliente = new javax.swing.JFormattedTextField();
        jtfRua = new javax.swing.JFormattedTextField();
        jtfCodProduto = new javax.swing.JFormattedTextField();
        ftfProduto = new javax.swing.JFormattedTextField();
        btProduto = new javax.swing.JButton();
        ftfQuantidade = new javax.swing.JFormattedTextField();
        ftfValorUnitario = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        btCliente = new javax.swing.JButton();
        ftfCliente = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        ftfDatav = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        abasVenda = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGradeItens = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbGrade = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        ftfSubTotal = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        ftfDesconto = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        ftfPago = new javax.swing.JFormattedTextField();
        jToolBar2 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btFinalizar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        ftfMarca = new javax.swing.JFormattedTextField();
        btAddCliente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfUf = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        ftfCodEmpresa = new javax.swing.JFormattedTextField();
        ftfEmpresa = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JFormattedTextField();
        lblUser = new javax.swing.JLabel();
        jcbForma = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        ftfTotal = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("PEDIDO DE VENDAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Vendas"));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("EMPRESA.:");

        ftfOperacao.setEditable(false);
        ftfOperacao.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        ftfOperacao.setEnabled(false);

        jtfCodCliente.setEditable(false);
        jtfCodCliente.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jtfCodCliente.setEnabled(false);
        jtfCodCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfCodCliente.setSelectionColor(new java.awt.Color(255, 0, 0));

        jtfRua.setEditable(false);
        jtfRua.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jtfRua.setEnabled(false);
        jtfRua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfRua.setSelectionColor(new java.awt.Color(255, 0, 0));
        jtfRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRuaActionPerformed(evt);
            }
        });

        jtfCodProduto.setEditable(false);
        jtfCodProduto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCodProduto.setEnabled(false);
        jtfCodProduto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        ftfProduto.setEditable(false);
        ftfProduto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Zoom.png"))); // NOI18N
        btProduto.setToolTipText("Localizar cliente");
        btProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btProduto.setEnabled(false);
        btProduto.setPreferredSize(new java.awt.Dimension(21, 21));
        btProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutoActionPerformed(evt);
            }
        });

        ftfQuantidade.setEnabled(false);
        ftfQuantidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ftfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfQuantidadeKeyPressed(evt);
            }
        });

        ftfValorUnitario.setEditable(false);
        ftfValorUnitario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("R$ UNITÁRIO.:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("QTDE.:");

        jtfCidade.setEditable(false);
        jtfCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfCidade.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jtfCidade.setEnabled(false);

        jtfNumero.setEditable(false);
        jtfNumero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfNumero.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jtfNumero.setEnabled(false);

        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Zoom.png"))); // NOI18N
        btCliente.setToolTipText("Localizar cliente");
        btCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btCliente.setEnabled(false);
        btCliente.setPreferredSize(new java.awt.Dimension(21, 21));
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        ftfCliente.setEditable(false);
        ftfCliente.setColumns(25);
        ftfCliente.setForeground(new java.awt.Color(51, 51, 255));
        ftfCliente.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        ftfCliente.setEnabled(false);
        ftfCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("CLIENTE.:");

        ftfDatav.setEditable(false);
        ftfDatav.setForeground(new java.awt.Color(51, 51, 255));
        ftfDatav.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        ftfDatav.setCaretColor(new java.awt.Color(51, 51, 255));
        ftfDatav.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        ftfDatav.setEnabled(false);
        ftfDatav.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ftfDatav.setSelectedTextColor(new java.awt.Color(51, 51, 255));
        ftfDatav.setSelectionColor(new java.awt.Color(51, 51, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("DATA.:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("PRODUTO.:");

        tbGradeItens.setModel(new VendaItemTableModel());
        jScrollPane1.setViewportView(tbGradeItens);

        abasVenda.addTab("PRODUTOS", jScrollPane1);

        tbGrade.setModel(new VendaTableModel());
        tbGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGradeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbGrade);

        abasVenda.addTab("VENDAS", jScrollPane3);

        jLabel9.setText("SUBTOTAL.:");

        ftfSubTotal.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        ftfSubTotal.setEnabled(false);
        ftfSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setText("% DESCONTO.:");

        ftfDesconto.setEnabled(false);
        ftfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfDescontoKeyPressed(evt);
            }
        });

        jLabel1.setText("R$ PAGO.:");

        ftfPago.setEnabled(false);

        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setRollover(true);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.setToolTipText("Nova Venda");
        btNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btNovo.setMaximumSize(new java.awt.Dimension(92, 35));
        btNovo.setPreferredSize(new java.awt.Dimension(70, 35));
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        btNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btNovoKeyPressed(evt);
            }
        });
        jToolBar2.add(btNovo);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("Finalizar Venda");
        btSalvar.setEnabled(false);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btSalvar.setMaximumSize(new java.awt.Dimension(92, 35));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jToolBar2.add(btSalvar);

        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/finalizar.png"))); // NOI18N
        btFinalizar.setText("Finalizar");
        btFinalizar.setEnabled(false);
        btFinalizar.setFocusable(false);
        btFinalizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btFinalizar.setMaximumSize(new java.awt.Dimension(92, 35));
        btFinalizar.setPreferredSize(new java.awt.Dimension(80, 41));
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });
        jToolBar2.add(btFinalizar);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("Cancelar Venda");
        btCancelar.setEnabled(false);
        btCancelar.setFocusable(false);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btCancelar.setMaximumSize(new java.awt.Dimension(92, 35));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jToolBar2.add(btCancelar);

        ftfMarca.setEditable(false);
        ftfMarca.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ftfMarca.setEnabled(false);
        ftfMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        btAddCliente.setToolTipText("Localizar cliente");
        btAddCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAddCliente.setEnabled(false);
        btAddCliente.setPreferredSize(new java.awt.Dimension(21, 21));
        btAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddClienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel10.setText("ENDEREÇO/RUA.:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setText("ESTADO.:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setText("CIDADE.:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel13.setText("NÚMERO.:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setText("MARCA.:");

        jtfUf.setEditable(false);
        jtfUf.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jtfUf.setEnabled(false);
        jtfUf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel15.setText("TIPO DE OPERAÇÃO.:");

        ftfCodEmpresa.setEditable(false);
        ftfCodEmpresa.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        ftfCodEmpresa.setEnabled(false);
        ftfCodEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        ftfEmpresa.setEditable(false);
        ftfEmpresa.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        ftfEmpresa.setEnabled(false);
        ftfEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel16.setText("USUÁRIO.:");

        jtfUsuario.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfUsuario.setEnabled(false);
        jtfUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jcbForma.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jcbForma.setEnabled(false);

        jLabel17.setText("FORMA DE PAGAMENTO.:");

        ftfTotal.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        ftfTotal.setEnabled(false);
        ftfTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel18.setText("TOTAL.:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abasVenda)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUsuario))
                    .addComponent(jcbForma, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ftfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ftfPago, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ftfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ftfCodEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(ftfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftfDatav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jtfCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jtfUf, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ftfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel8))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftfCodEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ftfDatav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ftfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(abasVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbForma, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftfPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutoActionPerformed
        BuscaProduto busca = new BuscaProduto(this);
        busca.setLocationRelativeTo(null);
        busca.setVisible(true);
    }//GEN-LAST:event_btProdutoActionPerformed

    private void addIten() {
        if (validarFormularioItens()) {
            abasVenda.setSelectedIndex(0);
            VendaItem iv = new VendaItem();
            iv.setProduto((Produto) ftfProduto.getValue());
            iv.setVenda(venda);
            iv.setQuantidade(Double.parseDouble(ftfQuantidade.getText()));
            iv.setVlr_unitario((Double) ftfValorUnitario.getValue());
            System.out.println("AKI " + iv.getProduto() + " " + iv.getVenda() + " " + iv.getQuantidade() + " " + iv.getVlr_unitario() + " " + iv.getValorTotal());
            venda.addItem(iv);

            VendaItemTableModel ivtm = (VendaItemTableModel) tbGradeItens.getModel();
            ivtm.setDados(venda.getItens());

            //ftfSubTotal.setValue(venda.getVlrsubtotal());
            ftfSubTotal.setText(new DecimalFormat("#,##0.00").format(venda.getVlrsubtotal()));
            ftfTotal.setText(new DecimalFormat("#,##0.00").format(venda.getVlrsubtotal()));
            //ftfTotal.setValue(venda.getVlrsubtotal());
            ftfDesconto.setEnabled(true);
            grade();
//            DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
//            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
//            DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
//
//            esquerda.setHorizontalAlignment(SwingConstants.LEFT);
//            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
//            direita.setHorizontalAlignment(SwingConstants.RIGHT);
//
//            tbGradeItens.getColumnModel().getColumn(0).setCellRenderer(direita);
//            tbGradeItens.getColumnModel().getColumn(1).setCellRenderer(esquerda);
//            tbGradeItens.getColumnModel().getColumn(2).setCellRenderer(centralizado);
//            tbGradeItens.getColumnModel().getColumn(3).setCellRenderer(centralizado);
//            tbGradeItens.getColumnModel().getColumn(4).setCellRenderer(direita);
//            tbGradeItens.getColumnModel().getColumn(5).setCellRenderer(direita);
//
//            tbGradeItens.getColumnModel().getColumn(0).setPreferredWidth(15);
//            tbGradeItens.getColumnModel().getColumn(1).setPreferredWidth(290);
//            tbGradeItens.getColumnModel().getColumn(2).setPreferredWidth(20);
//            tbGradeItens.getColumnModel().getColumn(3).setPreferredWidth(35);
//            tbGradeItens.getColumnModel().getColumn(4).setPreferredWidth(35);
//            tbGradeItens.getColumnModel().getColumn(5).setPreferredWidth(35);
            limpaFormularioItens();
            //jcbCondicao.setEnabled(true);
        }
    }

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        BuscaCliente busca = new BuscaCliente(this);
        busca.setLocationRelativeTo(null);
        busca.setVisible(true);
    }//GEN-LAST:event_btClienteActionPerformed

    private void jtfRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRuaActionPerformed

    private void tbGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGradeMouseClicked
        if (evt.getClickCount() == 2) {
            grade();
            abasVenda.setSelectedIndex(0);
            int linhaSelecionada = tbGrade.getSelectedRow();

            VendaTableModel vtm = (VendaTableModel) tbGrade.getModel();
            venda = vtm.getRowValue(linhaSelecionada);

            jtfCodCliente.setValue(venda.getCliente().getId());
            ftfCliente.setValue(venda.getCliente());
            ftfDatav.setValue(venda.getDatavenda());
            jtfRua.setValue(venda.getCliente().getRua());
            jtfNumero.setText(venda.getCliente().getNumero());
            jtfCidade.setText(venda.getCliente().getCidade());
            jtfUf.setValue(venda.getCliente().getEstado().getNome());
            ftfSubTotal.setValue(NFC.format(venda.getVlrsubtotal()));
            ftfTotal.setValue(NFC.format(venda.getCalcVlrTotal()));
            //jtfVlrVenda.setText(new DecimalFormat("#,##0.00").format(p.getVlrvenda()));
            combo();
            try {
                jcbForma.setSelectedItem(venda.getForma().getDescricao());
            } catch (Exception e) {

            }

            VendaItemTableModel tm = (VendaItemTableModel) tbGradeItens.getModel();
            tm.setDados(venda.getItens());

            habilitarFormulario(true);
        }
    }//GEN-LAST:event_tbGradeMouseClicked

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        abasVenda.setSelectedIndex(0);
        venda = new Venda();
        ftfDatav.setValue(new Date());
        habilitarFormulario(true);
        combo();
    }//GEN-LAST:event_btNovoActionPerformed

    private void combo() {
        fDAO = new PgFormaDAO();
        listaForma = fDAO.listarTodos();

        jcbForma.removeAllItems();
        for (PgForma ob : listaForma) {
            jcbForma.addItem(ob.getDescricao());
        }
        jcbForma.setSelectedIndex(-1);
    }

    private void btNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btNovoKeyPressed

    }//GEN-LAST:event_btNovoKeyPressed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        salvar(false);
    }//GEN-LAST:event_btSalvarActionPerformed

    public void salvar(boolean finalizar) {
        if (validarFormulario()) {
            venda.setEmpresa(emp);
            venda.setCliente((Cliente) ftfCliente.getValue());
            System.out.println("Cliente.:" + venda.getCliente());
            try {
                venda.setForma(listaForma.get(jcbForma.getSelectedIndex()));
                venda.setDesconto(Integer.parseInt(ftfDesconto.getText()));
            } catch (Exception e) {
                System.out.println("SEM FORMA DE PAGAMENTO...!");
            }
            venda.setDatavenda(new Date());

            if (finalizar) {
                venda.setSituacao(Situacao.FINALIZADA);
            } else {
                venda.setSituacao(Situacao.ABERTA);
            }

            // if (venda.getId() == 0) {
            try {
                vendaDAO.salvar(venda);
                if (finalizar) {
                    if ("CA".equals(venda.getForma().getCondicao().getTipo())) {
                        cartao(venda);
                    } else if ("CR".equals(venda.getForma().getCondicao().getTipo())) {
                        crediario(venda);
                    }
                }
                System.out.println(" Cliente:" + venda.getCliente().getId() + " - data:" + venda.getDatavenda() + " - Venda.:" + venda + " - " + venda.getId() + " Situacao.:" + venda.getSituacao());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao Inserir a Venda.!\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                System.out.println(" Cliente:" + venda.getCliente().getId() + " - Data:" + venda.getDatavenda() + " - Venda catch.: " + venda + " - " + venda.getId());
                return;
            }
            // } else {
            //  try {
            //    vendaDAO.salvar(venda);
//                    if (JOptionPane.showConfirmDialog(null, "Imprimir Venda? ", "Pergunta!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
//                        //imprimirVenda(venda);
//                    } else {
//                    }
            //  } catch (Exception ex) {
//                    JOptionPane.showMessageDialog(this, "Erro ao alterar a venda.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
//                    return;
            // }
            // }
            habilitarFormulario(false);
            carregarGrade();
        }
    }

    private void cartao(Venda venda) {
        ConciliacaoDAO carDAO = new ConciliacaoDAO();
        Calendar calendar = Calendar.getInstance();
        if (venda.getForma().getQtdParcela() > 0) {
            for (int i = 1; i <= venda.getForma().getQtdParcela(); i++) {
                Conciliacao cartao = new Conciliacao();

                cartao.setVenda(venda);
                cartao.setEmpresa(emp);
                cartao.setCliente(venda.getCliente());
                cartao.setPgcondicao(null);
                cartao.setDataPagamento(null);
                cartao.setParcela(i);
                cartao.setJuro(0.0);
                //vendaRecibo.setDesconto(0);
                cartao.setVlrTotal(venda.getVlrsubtotal() / venda.getForma().getQtdParcela());
                cartao.setMulta(0.0);
                calendar.add(Calendar.MONTH, 1);
                cartao.setDataVencimento(calendar.getTime());

                try {
                    carDAO.salvar(cartao);
                } catch (Exception ex) {
                    Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void crediario(Venda venda) {
        ContaReceberDAO conDAO = new ContaReceberDAO();
        Calendar calendar = Calendar.getInstance();
        if (venda.getForma().getQtdParcela() > 0) {
            for (int i = 1; i <= venda.getForma().getQtdParcela(); i++) {
                ContaReceber conta = new ContaReceber();

                conta.setVenda(venda);
                System.out.println("VENDA.:" + venda.getId());
                conta.setEmpresa(emp);
                conta.setCliente(venda.getCliente());
                conta.setPgforma(listaForma.get(jcbForma.getSelectedIndex()));
                conta.setData_pagamento(null);
                conta.setParcela(i);
                //cartao.setJuro(0.0);
                //vendaRecibo.setDesconto(0);
                conta.setVlr_total(venda.getVlrsubtotal() / venda.getForma().getQtdParcela());
                //cartao.setMulta(0.0);
                calendar.add(Calendar.MONTH, 1);
                conta.setData_vencimento(calendar.getTime());
                //if (conta.getId() != null) {
                try {
                    conDAO.salvar(conta);
                } catch (Exception ex) {
                    Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
                }
                //  }
            }
        }
    }

    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja Realmente Finalizar a Venda?");
        if (validarFinalizar()) {
            if (opcao == 0) {
                ProdutoDAO produtoDAO = new ProdutoDAO();
                for (VendaItem iv : venda.getItens()) {
                    try {
                        if (iv.getQuantidade() > produtoDAO.recuperar((long) iv.getProduto().getId()).getQuantidade()) {
                            JOptionPane.showMessageDialog(this, "Impossível Finalizar.\nProduto " + iv.getProduto() + " em falta no estoque.", "Alerta", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Erro ao Consultar o Estoque!", "Erro", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                salvar(true);
            }
        }
    }//GEN-LAST:event_btFinalizarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        habilitarFormulario(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddClienteActionPerformed
        ClienteView form = new ClienteView();
        Menu.desktopPane.add(form);
        form.setVisible(true);
        form.moveToFront();
        menuCliente.setEnabled(false);
        add = "on";
    }//GEN-LAST:event_btAddClienteActionPerformed

    private void ftfQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfQuantidadeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            addIten();
        }
    }//GEN-LAST:event_ftfQuantidadeKeyPressed

    private void ftfDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfDescontoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (!(ftfDesconto.getText().isEmpty())) {

                double subtotal = Double.parseDouble(ftfSubTotal.getText().replace(',', '.'));
                double desconto = Double.parseDouble(ftfDesconto.getText().replace(',', '.'));

                double vlrdesconto = ((subtotal * desconto) / 100);
                double total = (subtotal - vlrdesconto);

                ftfTotal.setValue(total);

            }
        }
    }//GEN-LAST:event_ftfDescontoKeyPressed

    private void habilitarFormulario(boolean ativo) {
        btNovo.setEnabled(!ativo);
        btSalvar.setEnabled(ativo);
        btFinalizar.setEnabled(ativo);
        btCancelar.setEnabled(ativo);
        ftfCliente.setEnabled(ativo);
        btCliente.setEnabled(ativo);
        btAddCliente.setEnabled(ativo);
        ftfDatav.setEnabled(ativo);
        //ftfValorTotal.setEnabled(ativo);
        ftfProduto.setEnabled(ativo);
        btProduto.setEnabled(ativo);
        ftfValorUnitario.setEnabled(ativo);
        //btAdicionarItem.setEnabled(ativo);
        //btRemoverItem.setEnabled(ativo);
        //tbGradeItens.setEnabled(!ativo);
        jcbForma.setEnabled(ativo);

        if (!ativo) {
            limpaFormulario();
        }
    }

    private void limpaFormulario() {
        venda = null;
        jtfCodCliente.setText("");
        ftfCliente.setValue(null);
        jtfRua.setText("");
        jtfNumero.setText("");
        jtfCidade.setText("");
        jtfUf.setText("");
        ftfDatav.setText("");
        ftfSubTotal.setValue(new Double(0));
        ftfTotal.setValue(new Double(0));
        ftfProduto.setValue(null);
        //spQuantidade.setValue(1);
        ftfValorUnitario.setValue(new Double(0));
        tbGradeItens.setModel(new VendaItemTableModel());
        //jcbCondicao.setSelectedItem(null);
        jcbForma.setSelectedItem(null);
        ftfDesconto.setValue("");
        ftfDesconto.setEnabled(false);
        limpaFormularioItens();
    }

    private void limpaFormularioItens() {
        jtfCodProduto.setValue(null);
        ftfProduto.setValue(null);
        ftfMarca.setValue(null);
        //spQuantidade.setValue(1);
        ftfQuantidade.setValue("1");
        ftfValorUnitario.setValue(new Double(0));
    }

    private boolean validarFinalizar() {
        if (jcbForma.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma FORMA DE PAGAMENTO.!", "Alerta", JOptionPane.WARNING_MESSAGE);
            jcbForma.requestFocus();
            return false;
        }
        return true;
    }

    private boolean validarFormulario() {
        if (ftfCliente.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Cliente inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfCliente.requestFocus();
            return false;
        }

        if (venda.quantidadeItens() == 0) {
            JOptionPane.showMessageDialog(this, "Quantidade de Itens Inválida.", "Alerta", JOptionPane.WARNING_MESSAGE);
            //tpConteudo.setSelectedIndex(1);
            return false;
        }
        return true;
    }

    private boolean validarFormularioItens() {
        if (!(ftfQuantidade.getText().length() > 0 && ftfQuantidade.getText() != null)) {
            JOptionPane.showMessageDialog(null, "Campo QUANTIDADE Deve ser Informado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            ftfQuantidade.requestFocus();
            return false;
        }
        if (ftfProduto.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Produto Inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfProduto.requestFocus();
            return false;
        }
        return true;
    }

    public void setCliente(Cliente cl) {
        jtfCodCliente.setValue(cl.getId());
        ftfCliente.setValue(cl);
        jtfRua.setValue(cl.getRua());
        jtfNumero.setText(cl.getNumero());
        jtfCidade.setText(cl.getCidade());
        jtfUf.setText(cl.getEstado().getUf());
    }

    public void setProduto(Produto p) {
        ftfProduto.setValue(p);
        jtfCodProduto.setValue(p.getId());
        ftfValorUnitario.setValue(p.getVlrvenda());
        ftfMarca.setValue(p.getMarca().getDescricao());
        ftfQuantidade.setEnabled(true);
        ftfQuantidade.requestFocus();
    }

    private void infos() {
        jtfUsuario.setText(Menu.lblUser.getText());

        ftfCodEmpresa.setValue(emp.getId());
        ftfEmpresa.setValue(emp);
    }

    private void grade() {
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();

        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);

        tbGradeItens.getColumnModel().getColumn(0).setCellRenderer(direita);
        tbGradeItens.getColumnModel().getColumn(1).setCellRenderer(esquerda);
        tbGradeItens.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        tbGradeItens.getColumnModel().getColumn(3).setCellRenderer(centralizado);
        tbGradeItens.getColumnModel().getColumn(4).setCellRenderer(direita);
        tbGradeItens.getColumnModel().getColumn(5).setCellRenderer(direita);

        tbGradeItens.getColumnModel().getColumn(0).setPreferredWidth(15);
        tbGradeItens.getColumnModel().getColumn(1).setPreferredWidth(290);
        tbGradeItens.getColumnModel().getColumn(2).setPreferredWidth(20);
        tbGradeItens.getColumnModel().getColumn(3).setPreferredWidth(35);
        tbGradeItens.getColumnModel().getColumn(4).setPreferredWidth(35);
        tbGradeItens.getColumnModel().getColumn(5).setPreferredWidth(35);
    }

    private void carregarGrade() {
        //abasVenda.setSelectedIndex(1);
        VendaTableModel tm = (VendaTableModel) tbGrade.getModel();
        try {
            tm.setDados(vendaDAO.listarTodos(emp.getId()));

            DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            DefaultTableCellRenderer direita = new DefaultTableCellRenderer();

            esquerda.setHorizontalAlignment(SwingConstants.LEFT);
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            direita.setHorizontalAlignment(SwingConstants.RIGHT);

            tbGrade.getColumnModel().getColumn(0).setCellRenderer(centralizado);
            tbGrade.getColumnModel().getColumn(1).setCellRenderer(direita);
            tbGrade.getColumnModel().getColumn(2).setCellRenderer(esquerda);
            tbGrade.getColumnModel().getColumn(3).setCellRenderer(centralizado);
            tbGrade.getColumnModel().getColumn(4).setCellRenderer(direita);
            tbGrade.getColumnModel().getColumn(5).setCellRenderer(centralizado);

            tbGrade.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbGrade.getColumnModel().getColumn(1).setPreferredWidth(20);
            tbGrade.getColumnModel().getColumn(2).setPreferredWidth(300);
            tbGrade.getColumnModel().getColumn(3).setPreferredWidth(30);
            tbGrade.getColumnModel().getColumn(4).setPreferredWidth(30);
            tbGrade.getColumnModel().getColumn(5).setPreferredWidth(14);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grade.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasVenda;
    private javax.swing.JButton btAddCliente;
    public static javax.swing.JButton btCancelar;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btFinalizar;
    public static javax.swing.JButton btNovo;
    private javax.swing.JButton btProduto;
    public static javax.swing.JButton btSalvar;
    private javax.swing.JFormattedTextField ftfCliente;
    private javax.swing.JFormattedTextField ftfCodEmpresa;
    private javax.swing.JFormattedTextField ftfDatav;
    private javax.swing.JFormattedTextField ftfDesconto;
    private javax.swing.JFormattedTextField ftfEmpresa;
    private javax.swing.JFormattedTextField ftfMarca;
    private javax.swing.JTextField ftfOperacao;
    private javax.swing.JFormattedTextField ftfPago;
    private javax.swing.JFormattedTextField ftfProduto;
    private javax.swing.JFormattedTextField ftfQuantidade;
    private javax.swing.JFormattedTextField ftfSubTotal;
    private javax.swing.JFormattedTextField ftfTotal;
    private javax.swing.JFormattedTextField ftfValorUnitario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JComboBox<String> jcbForma;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JFormattedTextField jtfCodCliente;
    private javax.swing.JFormattedTextField jtfCodProduto;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JFormattedTextField jtfRua;
    private javax.swing.JFormattedTextField jtfUf;
    public static javax.swing.JFormattedTextField jtfUsuario;
    public static javax.swing.JLabel lblUser;
    private javax.swing.JTable tbGrade;
    private javax.swing.JTable tbGradeItens;
    // End of variables declaration//GEN-END:variables
}
